package com.ragforge.ingestion.connector;

public enum ConnectorFailure {
    CHECKPOINT_INVALID,
    SOURCE_UNAVAILABLE,
    RULES_INVALID,
    PATH_INVALID,
    VERSION_MISMATCH,
    OBJECT_NOT_FOUND,
    CONTENT_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    CHECKPOINT_STALE,
    PERSISTENCE_INCOMPLETE,
    OUTBOX_PERSIST_FAILED
}
